name: Feature Request
description: Request a feature
title: "[FEATURE REQUEST]: "
labels: ["enhancement"]
assignees:
  - "Bhupesh-V"
body:
  - type: markdown
    attributes:
      value: |
        "Thanks for contributing to the community project!"
  - type: textarea
    id: feature-request
    attributes:
      label: Feature details?
      description: Tell us in detail about the feature you would like to see implemented?
      placeholder: Please include a detailed description of the feature/enhancement along with code snippets & examples if possible!
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/developersIndia/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
